name: ex05_image1   # 프로젝트 이름
description: "A new Flutter project."   # 설명
publish_to: 'none'
version: 1.0.0+1    # 버전 (앱 스토어 릴리즈 시 중요)
environment:        # Dart SDK 버전
  sdk: ^3.8.1       # sdk: ">=2.18.0 <3.0.0"

dependencies:       # 앱에서 사용하는 패키지들
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # http: ^0.13.4
  # provider: ^6.0.0

dev_dependencies:   # 개발 중에만 필요한 패키지들
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:            # 리소스(이미지, 폰트 등) 설정
  uses-material-design: true
  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic