{"Jnclluniv":
     [
         {"head": [
            {"list_total_count": 311},
            {"RESULT":
                 {"CODE": "INFO-000", "MESSAGE": "정상 처리되었습니다."}
            },
            {"api_version": "1.0"}
            ]
         },
         {"row": [
            {"SIGUN_NM": "수원시", "SIGUN_CD": "41110", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "경기대학교 조형대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "수원시", "SIGUN_CD": "41110", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "경기대학교 행정대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "수원시", "SIGUN_CD": "41110", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "경기대학교 행정사회복지대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "수원시", "SIGUN_CD": "41110", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "경기대학교 행정복지상담대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "수원시", "SIGUN_CD": "41110", "REG_NO": null, "SCHOOL_DIV_NM": "대학교", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "아주대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "수원시", "SIGUN_CD": "41110", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "아주대학교 IT융합대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "수원시", "SIGUN_CD": "41110", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "아주대학교 경영대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "수원시", "SIGUN_CD": "41110", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "아주대학교 공공정책대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "수원시", "SIGUN_CD": "41110", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "아주대학교 공학대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "수원시", "SIGUN_CD": "41110", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "아주대학교 교육대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "수원시", "SIGUN_CD": "41110", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "아주대학교 교통ITS대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "수원시", "SIGUN_CD": "41110", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "아주대학교 국제대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "수원시", "SIGUN_CD": "41110", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "아주대학교 글로벌제약임상대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "수원시", "SIGUN_CD": "41110", "REG_NO": null, "SCHOOL_DIV_NM": "일반대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "아주대학교 대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "수원시", "SIGUN_CD": "41110", "REG_NO": null, "SCHOOL_DIV_NM": "전문대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "아주대학교 법학전문대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "수원시", "SIGUN_CD": "41110", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "아주대학교 보건대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "수원시", "SIGUN_CD": "41110", "REG_NO": null, "SCHOOL_DIV_NM": "전문대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "아주대학교 의학전문대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "수원시", "SIGUN_CD": "41110", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "아주대학교 임상치의학대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "수원시", "SIGUN_CD": "41110", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "아주대학교 정보통신대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "수원시", "SIGUN_CD": "41110", "REG_NO": null, "SCHOOL_DIV_NM": "전문대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "아주대학교 정보통신전문대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "수원시", "SIGUN_CD": "41110", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "경기대학교 예술대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "수원시", "SIGUN_CD": "41110", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "성균관대학교 과학기술대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "수원시", "SIGUN_CD": "41110", "REG_NO": null, "SCHOOL_DIV_NM": "전문대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "성균관대학교 기술경영전문대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "수원시", "SIGUN_CD": "41110", "REG_NO": null, "SCHOOL_DIV_NM": "전문대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "성균관대학교 수자원전문대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "수원시", "SIGUN_CD": "41110", "REG_NO": null, "SCHOOL_DIV_NM": "전문대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "성균관대학교 의학전문대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "수원시", "SIGUN_CD": "41110", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "성균관대학교 임상간호대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "수원시", "SIGUN_CD": "41110", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "성균관대학교 임상약학대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "수원시", "SIGUN_CD": "41110", "REG_NO": null, "SCHOOL_DIV_NM": "전문대학", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "동남보건대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "수원시", "SIGUN_CD": "41110", "REG_NO": null, "SCHOOL_DIV_NM": "사이버대학(대학)", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "국제사이버대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "시흥시", "SIGUN_CD": "41390", "REG_NO": null, "SCHOOL_DIV_NM": "전문대학", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "경기과학기술대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "시흥시", "SIGUN_CD": "41390", "REG_NO": null, "SCHOOL_DIV_NM": "대학교", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "한국공학대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "시흥시", "SIGUN_CD": "41390", "REG_NO": null, "SCHOOL_DIV_NM": "산업대학", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "한국산업기술대학교(산업대)", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "시흥시", "SIGUN_CD": "41390", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "한국공학대학교 산업기술경영대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "시흥시", "SIGUN_CD": "41390", "REG_NO": null, "SCHOOL_DIV_NM": "일반대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "한국공학대학교 일반대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "시흥시", "SIGUN_CD": "41390", "REG_NO": null, "SCHOOL_DIV_NM": "전문대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "한국공학대학교 지식기반기술에너지대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "시흥시", "SIGUN_CD": "41390", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "한국산업기술대학교 산업기술경영대학원(산업대)", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "시흥시", "SIGUN_CD": "41390", "REG_NO": null, "SCHOOL_DIV_NM": "전문대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "한국산업기술대학교 지식기반기술에너지대학원(산업대)", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "안산시", "SIGUN_CD": "41270", "REG_NO": null, "SCHOOL_DIV_NM": "전문대학", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "신안산대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "안산시", "SIGUN_CD": "41270", "REG_NO": null, "SCHOOL_DIV_NM": "전문대학", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "서울예술대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "안산시", "SIGUN_CD": "41270", "REG_NO": null, "SCHOOL_DIV_NM": "전문대학", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "안산대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "안양시", "SIGUN_CD": "41170", "REG_NO": null, "SCHOOL_DIV_NM": "일반대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "성결대학교 일반대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "안양시", "SIGUN_CD": "41170", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "성결대학교 프라임(Prime) 대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "안양시", "SIGUN_CD": "41170", "REG_NO": null, "SCHOOL_DIV_NM": "전문대학", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "연성대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "양주시", "SIGUN_CD": "41630", "REG_NO": null, "SCHOOL_DIV_NM": "대학교", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "경동대학교", "FACLT_DIV_NM": "제4캠퍼스", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "양주시", "SIGUN_CD": "41630", "REG_NO": null, "SCHOOL_DIV_NM": "전문대학", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "서정대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "양주시", "SIGUN_CD": "41630", "REG_NO": null, "SCHOOL_DIV_NM": "대학교", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "예원예술대학교", "FACLT_DIV_NM": "제2캠퍼스", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "양주시", "SIGUN_CD": "41630", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "예원예술대학교 문화예술대학원", "FACLT_DIV_NM": "제2캠퍼스", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "양평군", "SIGUN_CD": "41830", "REG_NO": null, "SCHOOL_DIV_NM": "대학교", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "아신대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "양평군", "SIGUN_CD": "41830", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "아신대학교 다문화교육복지대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "양평군", "SIGUN_CD": "41830", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "아신대학교 교육대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "양평군", "SIGUN_CD": "41830", "REG_NO": null, "SCHOOL_DIV_NM": "일반대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "아신대학교 대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "양평군", "SIGUN_CD": "41830", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "아신대학교 복지대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "양평군", "SIGUN_CD": "41830", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "아신대학교 상담대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "양평군", "SIGUN_CD": "41830", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "아신대학교 선교대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "양평군", "SIGUN_CD": "41830", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "아신대학교 신학대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "여주시", "SIGUN_CD": "41670", "REG_NO": null, "SCHOOL_DIV_NM": "전문대학", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "여주대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "오산시", "SIGUN_CD": "41370", "REG_NO": null, "SCHOOL_DIV_NM": "전문대학", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "오산대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "오산시", "SIGUN_CD": "41370", "REG_NO": null, "SCHOOL_DIV_NM": "대학교", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "한신대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "오산시", "SIGUN_CD": "41370", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "한신대학교 교육대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "오산시", "SIGUN_CD": "41370", "REG_NO": null, "SCHOOL_DIV_NM": "일반대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "한신대학교 대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "오산시", "SIGUN_CD": "41370", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "한신대학교 문예창작대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "오산시", "SIGUN_CD": "41370", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "한신대학교 정신분석대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "용인시", "SIGUN_CD": "41460", "REG_NO": null, "SCHOOL_DIV_NM": "대학교", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "강남대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "용인시", "SIGUN_CD": "41460", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "강남대학교 경영대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "용인시", "SIGUN_CD": "41460", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "강남대학교 교육대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "용인시", "SIGUN_CD": "41460", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "강남대학교 국제대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "용인시", "SIGUN_CD": "41460", "REG_NO": null, "SCHOOL_DIV_NM": "일반대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "강남대학교 대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "용인시", "SIGUN_CD": "41460", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "강남대학교 부동산·법무·행정대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "용인시", "SIGUN_CD": "41460", "REG_NO": null, "SCHOOL_DIV_NM": "전문대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "강남대학교 사회복지전문대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "용인시", "SIGUN_CD": "41460", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "강남대학교 실천신학대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "용인시", "SIGUN_CD": "41460", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "강남대학교 융복합대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "용인시", "SIGUN_CD": "41460", "REG_NO": null, "SCHOOL_DIV_NM": "대학교", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "루터대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "용인시", "SIGUN_CD": "41460", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "루터대학교 대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "용인시", "SIGUN_CD": "41460", "REG_NO": null, "SCHOOL_DIV_NM": "전문대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "경희대학교 국제대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "용인시", "SIGUN_CD": "41460", "REG_NO": null, "SCHOOL_DIV_NM": "전문대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "경희대학교 동서의학대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "용인시", "SIGUN_CD": "41460", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "경희대학교 아트퓨전디자인대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "용인시", "SIGUN_CD": "41460", "REG_NO": null, "SCHOOL_DIV_NM": "전문대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "경희대학교 체육대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "용인시", "SIGUN_CD": "41460", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "경희대학교 테크노경영대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "용인시", "SIGUN_CD": "41460", "REG_NO": null, "SCHOOL_DIV_NM": "대학교", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "칼빈대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "용인시", "SIGUN_CD": "41460", "REG_NO": null, "SCHOOL_DIV_NM": "일반대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "칼빈대학교 대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "안산시", "SIGUN_CD": "41270", "REG_NO": null, "SCHOOL_DIV_NM": "대학교", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "한양대학교(ERICA)", "FACLT_DIV_NM": "분교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "안산시", "SIGUN_CD": "41270", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "한양대학교(ERICA) 공학기술대학원", "FACLT_DIV_NM": "분교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "안산시", "SIGUN_CD": "41270", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "한양대학교(ERICA) 기업경영대학원", "FACLT_DIV_NM": "분교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "안산시", "SIGUN_CD": "41270", "REG_NO": null, "SCHOOL_DIV_NM": "일반대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "한양대학교(ERICA) 대학원", "FACLT_DIV_NM": "분교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "안산시", "SIGUN_CD": "41270", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "한양대학교(ERICA) 문화산업대학원", "FACLT_DIV_NM": "분교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "안산시", "SIGUN_CD": "41270", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "한양대학교(ERICA) 예술디자인대학원", "FACLT_DIV_NM": "분교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "안산시", "SIGUN_CD": "41270", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "한양대학교(ERICA) 융합산업대학원", "FACLT_DIV_NM": "분교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "안성시", "SIGUN_CD": "41550", "REG_NO": null, "SCHOOL_DIV_NM": "기능대학", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "한국폴리텍 특성화대학 반도체융합캠퍼스", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "안성시", "SIGUN_CD": "41550", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "중앙대학교 창업경영대학원", "FACLT_DIV_NM": "제2캠퍼스", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "안성시", "SIGUN_CD": "41550", "REG_NO": null, "SCHOOL_DIV_NM": "대학교", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "중앙대학교", "FACLT_DIV_NM": "제2캠퍼스", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "안성시", "SIGUN_CD": "41550", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "중앙대학교 국악교육대학원", "FACLT_DIV_NM": "제2캠퍼스", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "안성시", "SIGUN_CD": "41550", "REG_NO": null, "SCHOOL_DIV_NM": "일반대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "중앙대학교 대학원", "FACLT_DIV_NM": "제2캠퍼스", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "안성시", "SIGUN_CD": "41550", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "중앙대학교 산업창업경영대학원", "FACLT_DIV_NM": "제2캠퍼스", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "안성시", "SIGUN_CD": "41550", "REG_NO": null, "SCHOOL_DIV_NM": "전문대학", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "동아방송예술대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "안성시", "SIGUN_CD": "41550", "REG_NO": null, "SCHOOL_DIV_NM": "전문대학", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "두원공과대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "안성시", "SIGUN_CD": "41550", "REG_NO": null, "SCHOOL_DIV_NM": "대학교", "PLVTINST_DIV_NM": "국립",
             "FACLT_NM": "한경대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "안성시", "SIGUN_CD": "41550", "REG_NO": null, "SCHOOL_DIV_NM": "산업대학", "PLVTINST_DIV_NM": "국립",
             "FACLT_NM": "한경대학교(산업대)", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "안성시", "SIGUN_CD": "41550", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "국립",
             "FACLT_NM": "한경대학교 공공정책대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "안성시", "SIGUN_CD": "41550", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "국립",
             "FACLT_NM": "한경대학교 공공정책대학원(산업대)", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "안성시", "SIGUN_CD": "41550", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "국립",
             "FACLT_NM": "한경대학교 국제개발협력대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "안성시", "SIGUN_CD": "41550", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "국립",
             "FACLT_NM": "한경대학교 국제개발협력대학원(산업대)", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "안성시", "SIGUN_CD": "41550", "REG_NO": null, "SCHOOL_DIV_NM": "전문대학원", "PLVTINST_DIV_NM": "국립",
             "FACLT_NM": "한경대학교 미래융합기술대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "안성시", "SIGUN_CD": "41550", "REG_NO": null, "SCHOOL_DIV_NM": "전문대학원", "PLVTINST_DIV_NM": "국립",
             "FACLT_NM": "한경대학교 미래융합기술대학원(산업대)", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "안성시", "SIGUN_CD": "41550", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "국립",
             "FACLT_NM": "한경대학교 산업대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "안성시", "SIGUN_CD": "41550", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "국립",
             "FACLT_NM": "한경대학교 산업대학원(산업대)", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "안성시", "SIGUN_CD": "41550", "REG_NO": null, "SCHOOL_DIV_NM": "일반대학원", "PLVTINST_DIV_NM": "국립",
             "FACLT_NM": "한경대학교 일반대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "안양시", "SIGUN_CD": "41170", "REG_NO": null, "SCHOOL_DIV_NM": "전문대학", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "대림대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "안양시", "SIGUN_CD": "41170", "REG_NO": null, "SCHOOL_DIV_NM": "대학교", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "안양대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "안양시", "SIGUN_CD": "41170", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "안양대학교 경영행정대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "안양시", "SIGUN_CD": "41170", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "안양대학교 교육대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "안양시", "SIGUN_CD": "41170", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "안양대학교 글로벌대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "안양시", "SIGUN_CD": "41170", "REG_NO": null, "SCHOOL_DIV_NM": "일반대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "안양대학교 대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "안양시", "SIGUN_CD": "41170", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "안양대학교 신학대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "안양시", "SIGUN_CD": "41170", "REG_NO": null, "SCHOOL_DIV_NM": "교육대학", "PLVTINST_DIV_NM": "국립",
             "FACLT_NM": "경인교육대학교", "FACLT_DIV_NM": "제2캠퍼스", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "안양시", "SIGUN_CD": "41170", "REG_NO": null, "SCHOOL_DIV_NM": "대학교", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "성결대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "안양시", "SIGUN_CD": "41170", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "성결대학교 교육대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "안양시", "SIGUN_CD": "41170", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "성결대학교 사회복지대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "안양시", "SIGUN_CD": "41170", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "성결대학교 성결신학대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "안양시", "SIGUN_CD": "41170", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "성결대학교 신학대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "안양시", "SIGUN_CD": "41170", "REG_NO": null, "SCHOOL_DIV_NM": "전문대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "성결대학교 신학전문대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "고양시", "SIGUN_CD": "41280", "REG_NO": null, "SCHOOL_DIV_NM": "전문대학", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "농협대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "고양시", "SIGUN_CD": "41280", "REG_NO": null, "SCHOOL_DIV_NM": "대학교", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "한국항공대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "고양시", "SIGUN_CD": "41280", "REG_NO": null, "SCHOOL_DIV_NM": "일반대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "한국항공대학교 대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "고양시", "SIGUN_CD": "41280", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "한국항공대학교 항공경영대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "고양시", "SIGUN_CD": "41280", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "한국항공대학교 항공산업경영대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "과천시", "SIGUN_CD": "41290", "REG_NO": null, "SCHOOL_DIV_NM": "각종학교(전문)", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "구세군사관학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "광주시", "SIGUN_CD": "41610", "REG_NO": null, "SCHOOL_DIV_NM": "대학교", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "서울장신대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "광주시", "SIGUN_CD": "41610", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "서울장신대학교 교회음악대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "광주시", "SIGUN_CD": "41610", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "서울장신대학교 사회복지상담대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "광주시", "SIGUN_CD": "41610", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "서울장신대학교 신학대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "광주시", "SIGUN_CD": "41610", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "서울장신대학교 영성심리치유대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "광주시", "SIGUN_CD": "41610", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "서울장신대학교 예배찬양사역대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "광주시", "SIGUN_CD": "41610", "REG_NO": null, "SCHOOL_DIV_NM": "일반대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "서울장신대학교 일반대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "광주시", "SIGUN_CD": "41610", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "서울장신대학교 자연치유선교대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "광주시", "SIGUN_CD": "41610", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "서울장신대학교 전인치유선교대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "광주시", "SIGUN_CD": "41610", "REG_NO": null, "SCHOOL_DIV_NM": "전문대학", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "동원대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "광주시", "SIGUN_CD": "41610", "REG_NO": null, "SCHOOL_DIV_NM": "기능대학", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "ICT폴리텍대학", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "군포시", "SIGUN_CD": "41410", "REG_NO": null, "SCHOOL_DIV_NM": "대학교", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "한세대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "군포시", "SIGUN_CD": "41410", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "한세대학교 경찰법무경영대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "군포시", "SIGUN_CD": "41410", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "한세대학교 경찰법무대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "군포시", "SIGUN_CD": "41410", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "한세대학교 공공정책대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "군포시", "SIGUN_CD": "41410", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "한세대학교 공학대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "군포시", "SIGUN_CD": "41410", "REG_NO": null, "SCHOOL_DIV_NM": "일반대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "한세대학교 대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "군포시", "SIGUN_CD": "41410", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "한세대학교 사회복지대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "군포시", "SIGUN_CD": "41410", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "한세대학교 스포츠경영대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "군포시", "SIGUN_CD": "41410", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "한세대학교 심리상담대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "군포시", "SIGUN_CD": "41410", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "한세대학교 영산신학대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "군포시", "SIGUN_CD": "41410", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "한세대학교 치료상담대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "군포시", "SIGUN_CD": "41410", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "한세대학교 피아노페다고지대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "군포시", "SIGUN_CD": "41410", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "한세대학교 간호복지대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "군포시", "SIGUN_CD": "41410", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "한세대학교 공연예술대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "군포시", "SIGUN_CD": "41410", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "한세대학교 보건융합대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "군포시", "SIGUN_CD": "41410", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "한세대학교 산업보안안전대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "군포시", "SIGUN_CD": "41410", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "한세대학교 합창지휘대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "군포시", "SIGUN_CD": "41410", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "한세대학교 예술대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "군포시", "SIGUN_CD": "41410", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "한세대학교 휴먼서비스대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "김포시", "SIGUN_CD": "41570", "REG_NO": null, "SCHOOL_DIV_NM": "대학교", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "중앙승가대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "김포시", "SIGUN_CD": "41570", "REG_NO": null, "SCHOOL_DIV_NM": "일반대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "중앙승가대학교 대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "김포시", "SIGUN_CD": "41570", "REG_NO": null, "SCHOOL_DIV_NM": "전문대학", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "김포대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "남양주시", "SIGUN_CD": "41360", "REG_NO": null, "SCHOOL_DIV_NM": "전문대학", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "경복대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "남양주시", "SIGUN_CD": "41360", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "경희대학교 평화복지대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "동두천시", "SIGUN_CD": "41250", "REG_NO": null, "SCHOOL_DIV_NM": "대학교", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "신한대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "동두천시", "SIGUN_CD": "41250", "REG_NO": null, "SCHOOL_DIV_NM": "대학교", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "한북대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "동두천시", "SIGUN_CD": "41250", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "신한대학교 보건대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "동두천시", "SIGUN_CD": "41250", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "신한대학교 생활문화대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "동두천시", "SIGUN_CD": "41250", "REG_NO": null, "SCHOOL_DIV_NM": "일반대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "신한대학교 일반대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "동두천시", "SIGUN_CD": "41250", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "신한대학교 지식복지대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "동두천시", "SIGUN_CD": "41250", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "신한대학교 평생학습중심대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "부천시", "SIGUN_CD": "41190", "REG_NO": null, "SCHOOL_DIV_NM": "전문대학", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "유한대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "부천시", "SIGUN_CD": "41190", "REG_NO": null, "SCHOOL_DIV_NM": "대학교", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "서울신학대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "부천시", "SIGUN_CD": "41190", "REG_NO": null, "SCHOOL_DIV_NM": "일반대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "서울신학대학교 대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "부천시", "SIGUN_CD": "41190", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "서울신학대학교 사회복지대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "부천시", "SIGUN_CD": "41190", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "서울신학대학교 상담대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "부천시", "SIGUN_CD": "41190", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "서울신학대학교 설교대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "부천시", "SIGUN_CD": "41190", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "서울신학대학교 신학대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "부천시", "SIGUN_CD": "41190", "REG_NO": null, "SCHOOL_DIV_NM": "전문대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "서울신학대학교 신학전문대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "부천시", "SIGUN_CD": "41190", "REG_NO": null, "SCHOOL_DIV_NM": "전문대학", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "부천대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "부천시", "SIGUN_CD": "41190", "REG_NO": null, "SCHOOL_DIV_NM": "대학교", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "가톨릭대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "부천시", "SIGUN_CD": "41190", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "가톨릭대학교 교육대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "부천시", "SIGUN_CD": "41190", "REG_NO": null, "SCHOOL_DIV_NM": "일반대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "가톨릭대학교 대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "부천시", "SIGUN_CD": "41190", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "가톨릭대학교 교회법대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "부천시", "SIGUN_CD": "41190", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "서울신학대학교 교회성장대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "성남시", "SIGUN_CD": "41130", "REG_NO": null, "SCHOOL_DIV_NM": "전문대학", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "동서울대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "성남시", "SIGUN_CD": "41130", "REG_NO": null, "SCHOOL_DIV_NM": "대학교", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "을지대학교", "FACLT_DIV_NM": "제2캠퍼스", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "성남시", "SIGUN_CD": "41130", "REG_NO": null, "SCHOOL_DIV_NM": "대학교", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "가천대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "성남시", "SIGUN_CD": "41130", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "가천대학교 게임대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "성남시", "SIGUN_CD": "41130", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "가천대학교 경영대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "성남시", "SIGUN_CD": "41130", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "가천대학교 교육대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "성남시", "SIGUN_CD": "41130", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "가천대학교 사회정책대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "성남시", "SIGUN_CD": "41130", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "가천대학교 산업환경대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "성남시", "SIGUN_CD": "41130", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "가천대학교 소프트웨어대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "성남시", "SIGUN_CD": "41130", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "가천대학교 스포츠문화대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "성남시", "SIGUN_CD": "41130", "REG_NO": null, "SCHOOL_DIV_NM": "일반대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "가천대학교 일반대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "성남시", "SIGUN_CD": "41130", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "가천대학교 특수치료대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "성남시", "SIGUN_CD": "41130", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "가천대학교 환경디자인대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "성남시", "SIGUN_CD": "41130", "REG_NO": null, "SCHOOL_DIV_NM": "기능대학", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "한국폴리텍 I 대학 성남캠퍼스", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "성남시", "SIGUN_CD": "41130", "REG_NO": null, "SCHOOL_DIV_NM": "전문대학", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "신구대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "수원시", "SIGUN_CD": "41110", "REG_NO": null, "SCHOOL_DIV_NM": "전문대학", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "수원여자대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "수원시", "SIGUN_CD": "41110", "REG_NO": null, "SCHOOL_DIV_NM": "대학교", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "경기대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "수원시", "SIGUN_CD": "41110", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "경기대학교 건설산업대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "수원시", "SIGUN_CD": "41110", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "경기대학교 공학대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "수원시", "SIGUN_CD": "41110", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "경기대학교 교육대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "수원시", "SIGUN_CD": "41110", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "경기대학교 미술디자인대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "수원시", "SIGUN_CD": "41110", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "경기대학교 산업정보대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "수원시", "SIGUN_CD": "41110", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "경기대학교 스포츠과학대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "용인시", "SIGUN_CD": "41460", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "칼빈신학대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "용인시", "SIGUN_CD": "41460", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "단국대학교 정보융합기술창업대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "용인시", "SIGUN_CD": "41460", "REG_NO": null, "SCHOOL_DIV_NM": "대학교", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "단국대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "용인시", "SIGUN_CD": "41460", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "단국대학교 경영대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "용인시", "SIGUN_CD": "41460", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "단국대학교 교육대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "용인시", "SIGUN_CD": "41460", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "단국대학교 국제대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "용인시", "SIGUN_CD": "41460", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "단국대학교 문화예술대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "용인시", "SIGUN_CD": "41460", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "단국대학교 부동산건설대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "용인시", "SIGUN_CD": "41460", "REG_NO": null, "SCHOOL_DIV_NM": "전문대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "단국대학교 영화콘텐츠전문대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "용인시", "SIGUN_CD": "41460", "REG_NO": null, "SCHOOL_DIV_NM": "일반대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "단국대학교 일반대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "용인시", "SIGUN_CD": "41460", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "단국대학교 정보·지식재산대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "용인시", "SIGUN_CD": "41460", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "단국대학교 특수교육대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "용인시", "SIGUN_CD": "41460", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "단국대학교 행정법무대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "용인시", "SIGUN_CD": "41460", "REG_NO": null, "SCHOOL_DIV_NM": "전문대학", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "용인예술과학대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "용인시", "SIGUN_CD": "41460", "REG_NO": null, "SCHOOL_DIV_NM": "대학교", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "명지대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "용인시", "SIGUN_CD": "41460", "REG_NO": null, "SCHOOL_DIV_NM": "일반대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "명지대학교 대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "용인시", "SIGUN_CD": "41460", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "명지대학교 산업대학원", "FACLT_DIV_NM": "제2캠퍼스", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "용인시", "SIGUN_CD": "41460", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "총신대학교 신학대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "용인시", "SIGUN_CD": "41460", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "용인대학교 스포츠웰니스산업대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "용인시", "SIGUN_CD": "41460", "REG_NO": null, "SCHOOL_DIV_NM": "대학교", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "용인대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "용인시", "SIGUN_CD": "41460", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "용인대학교 경영대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "용인시", "SIGUN_CD": "41460", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "용인대학교 교육대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "용인시", "SIGUN_CD": "41460", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "용인대학교 문화예술대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "용인시", "SIGUN_CD": "41460", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "용인대학교 문화재대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "용인시", "SIGUN_CD": "41460", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "용인대학교 예술대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "용인시", "SIGUN_CD": "41460", "REG_NO": null, "SCHOOL_DIV_NM": "일반대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "용인대학교 일반대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "용인시", "SIGUN_CD": "41460", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "용인대학교 재활보건과학대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "용인시", "SIGUN_CD": "41460", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "용인대학교 재활복지대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "용인시", "SIGUN_CD": "41460", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "용인대학교 체육과학대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "용인시", "SIGUN_CD": "41460", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "용인대학교 태권도대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "용인시", "SIGUN_CD": "41460", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "용인대학교 통일대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "의왕시", "SIGUN_CD": "41430", "REG_NO": null, "SCHOOL_DIV_NM": "전문대학", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "계원예술대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "의정부시", "SIGUN_CD": "41150", "REG_NO": null, "SCHOOL_DIV_NM": "대학교", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "을지대학교", "FACLT_DIV_NM": "제3캠퍼스", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "의정부시", "SIGUN_CD": "41150", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "을지대학교 보건대학원", "FACLT_DIV_NM": "제3캠퍼스", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "의정부시", "SIGUN_CD": "41150", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "을지대학교 보건복지대학원", "FACLT_DIV_NM": "제3캠퍼스", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "의정부시", "SIGUN_CD": "41150", "REG_NO": null, "SCHOOL_DIV_NM": "일반대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "을지대학교 일반대학원", "FACLT_DIV_NM": "제3캠퍼스", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "의정부시", "SIGUN_CD": "41150", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "을지대학교 임상간호대학원", "FACLT_DIV_NM": "제3캠퍼스", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "의정부시", "SIGUN_CD": "41150", "REG_NO": null, "SCHOOL_DIV_NM": "전문대학", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "경민대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "의정부시", "SIGUN_CD": "41150", "REG_NO": null, "SCHOOL_DIV_NM": "대학교", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "신한대학교", "FACLT_DIV_NM": "제2캠퍼스", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "의정부시", "SIGUN_CD": "41150", "REG_NO": null, "SCHOOL_DIV_NM": "전문대학", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "신흥대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "이천시", "SIGUN_CD": "41500", "REG_NO": null, "SCHOOL_DIV_NM": "전문대학", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "청강문화산업대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "이천시", "SIGUN_CD": "41500", "REG_NO": null, "SCHOOL_DIV_NM": "전문대학", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "한국관광대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "파주시", "SIGUN_CD": "41480", "REG_NO": null, "SCHOOL_DIV_NM": "전문대학", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "웅지세무대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "평택시", "SIGUN_CD": "41220", "REG_NO": null, "SCHOOL_DIV_NM": "전문대학", "PLVTINST_DIV_NM": "국립",
             "FACLT_NM": "한국복지대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "평택시", "SIGUN_CD": "41220", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "평택대학교 글로벌비즈니스대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null,
             "REFINE_ROADNM_ADDR": null, "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "평택시", "SIGUN_CD": "41220", "REG_NO": null, "SCHOOL_DIV_NM": "대학교", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "평택대학교", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null},
            {"SIGUN_NM": "평택시", "SIGUN_CD": "41220", "REG_NO": null, "SCHOOL_DIV_NM": "특수대학원", "PLVTINST_DIV_NM": "사립",
             "FACLT_NM": "평택대학교 교육대학원", "FACLT_DIV_NM": "본교", "RM": null, "REFINE_LOTNO_ADDR": null, "REFINE_ROADNM_ADDR": null,
             "REFINE_ZIP_CD": null, "REFINE_WGS84_LOGT": null, "REFINE_WGS84_LAT": null}]}]}
